name: LLM_RA

channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.10
  - notebook=6.5.4
  - pyyaml=6.0
  - pip=23.0.1
  - pip:
    - langchain
    - openai
    - "pinecone-client[grpc]"
    - python-dotenv
    - pymupdf
    - rich
    - streamlit